Small improvements
hypeJunction/Elgg-countries pull request #1
Opened 2017-01-14 21:25 UTC by nlybe

- Countries input is now compatible with profile_manager plugin
- Added option to set default country in settings
- Checked compatibility with Elgg 2.x

2017-01-15 21:17 UTC, hypeJunction requested changes

2017-01-15 21:17 UTC, hypeJunction commented on manifest.xml
> +        <version>2.2</version>
Leave this as is. The only change that requires 2.2 is elgg_view_input which is unnecessary

2017-01-15 21:17 UTC, hypeJunction commented on languages/en.php
> -	'country:AD' => 'Andorra',
Your indentation settings are not in line with Elgg coding standards. We use 1 tab

2017-01-15 21:17 UTC, hypeJunction commented on manifest.xml
> +    <version type="dist">2.2.0</version>
My grunt script automatically iterates the version during releases. Leave as is

2017-01-15 21:17 UTC, hypeJunction commented on CHANGES.md
> +Elgg Countries Plugin - CHANGE LOG
My grunt script automatically creates a changelogs from commit messages. Use angular style commit messages for each feature and they will appear in the changelog

2017-01-15 21:17 UTC, hypeJunction commented on start.php
> +function elgg_get_default_country() {
Not needed. Just read the plugin setting in the input view

2017-01-15 21:17 UTC, hypeJunction commented on views/default/input/country.php
> +echo elgg_view_input('dropdown', $vars);
elgg_view_input generates wrapper markup. You don't want that

2017-01-15 21:17 UTC, hypeJunction commented on views/default/plugins/countries/settings.php
> +$basic_settings = elgg_format_element('div', [], elgg_view_input('dropdown', array(
No need to wrap. Use input/country view

2017-01-16 00:57 UTC, nlybe commented
Followed your suggestions, hopefully

2017-01-16 00:57 UTC, closed without merging